require('dotenv').config();
const express=require('express'),cors=require('cors'),helmet=require('helmet'),morgan=require('morgan'),rateLimit=require('express-rate-limit'),path=require('path');
const app=express(),PORT=process.env.PORT||3000,C=process.env.CREATOR||'CrazyApi',START=Date.now();
let totalReqs=0;
app.use(cors());app.use(helmet({contentSecurityPolicy:false}));app.use(morgan('tiny'));
app.use(express.json({limit:'10mb'}));app.use(express.urlencoded({extended:true}));
app.use('/api/',rateLimit({windowMs:60000,max:200,message:{status:false,creator:C,error:'Rate limit: 200 req/min max.'},standardHeaders:true,legacyHeaders:false}));
app.use('/api/',(req,res,next)=>{totalReqs++;next();});
app.use(express.static(path.join(__dirname,'public')));
const {requireApiKey}=require('./middleware/auth');
app.use('/api/ai',        requireApiKey,require('./routes/ai'));
app.use('/api/downloader',requireApiKey,require('./routes/downloader'));
app.use('/api/tools',     requireApiKey,require('./routes/tools'));
app.use('/api/anime',     requireApiKey,require('./routes/anime'));
app.use('/api/search',    requireApiKey,require('./routes/search'));
app.use('/api/sports',    requireApiKey,require('./routes/sports'));
app.use('/api/stalker',   requireApiKey,require('./routes/stalker'));
app.use('/api/checker',   requireApiKey,require('./routes/checker'));
app.use('/api/tempgen',   requireApiKey,require('./routes/tempgen'));
app.use('/api/shortener', requireApiKey,require('./routes/shortener'));
app.use('/api/fun',       requireApiKey,require('./routes/fun'));
app.use('/auth',                        require('./routes/auth'));
const fmt=s=>`${Math.floor(s/3600)}h ${Math.floor((s%3600)/60)}m ${s%60}s`;
app.get('/api/stats',(req,res)=>res.json({status:true,creator:C,version:'3.0.0',uptime:fmt(Math.floor((Date.now()-START)/1000)),memory_mb:Math.round(process.memoryUsage().heapUsed/1024/1024),total_requests:totalReqs,endpoints:130,categories:11,online:true}));
app.use('/api/*',(req,res)=>res.status(404).json({status:false,creator:C,error:`Endpoint not found: ${req.path}`}));
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.listen(PORT,()=>{console.log(`\n🚀 CrazyApi v3.0 → http://localhost:${PORT}\n🔑 Supabase: ${process.env.SUPABASE_URL?'✅ Connected':'⚠️  Dev mode'}\n`);});
