const express=require('express'),router=express.Router(),axios=require('axios'),{C}=require('../middleware/auth');
async function poll(p,m='openai'){const r=await axios.get(`https://text.pollinations.ai/${encodeURIComponent(p)}?model=${m}&seed=${Math.floor(Math.random()*99999)}`,{timeout:30000});return typeof r.data==='string'?r.data.trim():JSON.stringify(r.data);}
function img(p,m='flux',w=1024,h=1024){return `https://image.pollinations.ai/prompt/${encodeURIComponent(p)}?model=${m}&width=${w}&height=${h}&seed=${Math.floor(Math.random()*99999)}&nologo=true`;}
router.get('/ai',        async(req,res)=>{const{q}=req.query;if(!q)return res.json({status:false,creator:C(),error:'Missing q'});try{res.json({status:true,creator:C(),result:await poll(q)});}catch(e){res.json({status:false,creator:C(),error:e.message});}});
router.get('/gpt4',      async(req,res)=>{const{q}=req.query;if(!q)return res.json({status:false,creator:C(),error:'Missing q'});try{res.json({status:true,creator:C(),model:'gpt-4o',result:await poll(q,'openai-large')});}catch(e){res.json({status:false,creator:C(),error:e.message});}});
router.get('/gpt4mini',  async(req,res)=>{const{q}=req.query;if(!q)return res.json({status:false,creator:C(),error:'Missing q'});try{res.json({status:true,creator:C(),model:'gpt-4o-mini',result:await poll(q)});}catch(e){res.json({status:false,creator:C(),error:e.message});}});
router.get('/gemini',    async(req,res)=>{const{q}=req.query;if(!q)return res.json({status:false,creator:C(),error:'Missing q'});try{res.json({status:true,creator:C(),model:'gemini',result:await poll(q,'gemini')});}catch(e){res.json({status:false,creator:C(),error:e.message});}});
router.get('/deepseek',  async(req,res)=>{const{q}=req.query;if(!q)return res.json({status:false,creator:C(),error:'Missing q'});try{res.json({status:true,creator:C(),model:'deepseek',result:await poll(q,'deepseek')});}catch(e){res.json({status:false,creator:C(),error:e.message});}});
router.get('/llama',     async(req,res)=>{const{q}=req.query;if(!q)return res.json({status:false,creator:C(),error:'Missing q'});try{res.json({status:true,creator:C(),model:'llama',result:await poll(q,'llama')});}catch(e){res.json({status:false,creator:C(),error:e.message});}});
router.get('/mistral',   async(req,res)=>{const{q}=req.query;if(!q)return res.json({status:false,creator:C(),error:'Missing q'});try{res.json({status:true,creator:C(),model:'mistral',result:await poll(q,'mistral')});}catch(e){res.json({status:false,creator:C(),error:e.message});}});
router.get('/custom',    async(req,res)=>{const{q,prompt='You are a helpful assistant.'}=req.query;if(!q)return res.json({status:false,creator:C(),error:'Missing q'});try{res.json({status:true,creator:C(),result:await poll(`${prompt}\n\nUser: ${q}`)});}catch(e){res.json({status:false,creator:C(),error:e.message});}});
router.get('/muslim',    async(req,res)=>{const{q}=req.query;if(!q)return res.json({status:false,creator:C(),error:'Missing q'});try{res.json({status:true,creator:C(),result:await poll(`You are an Islamic AI with deep Quran knowledge. Answer Islamically: ${q}`)});}catch(e){res.json({status:false,creator:C(),error:e.message});}});
router.get('/imagine',   (req,res)=>{const{prompt,model='flux',width='1024',height='1024'}=req.query;if(!prompt)return res.json({status:false,creator:C(),error:'Missing prompt'});res.json({status:true,creator:C(),prompt,model,result:img(prompt,model,parseInt(width),parseInt(height))});});
router.get('/flux',      (req,res)=>{const{prompt,ratio='1:1'}=req.query;if(!prompt)return res.json({status:false,creator:C(),error:'Missing prompt'});const s={'1:1':'1024x1024','16:9':'1920x1080','9:16':'1080x1920','4:3':'1280x960','3:4':'960x1280'};const[w,h]=(s[ratio]||'1024x1024').split('x');res.json({status:true,creator:C(),prompt,result:img(prompt,'flux',+w,+h)});});
router.get('/sora',      (req,res)=>{const{prompt}=req.query;if(!prompt)return res.json({status:false,creator:C(),error:'Missing prompt'});res.json({status:true,creator:C(),prompt,result:img(prompt,'flux')});});
router.get('/deepai',    (req,res)=>{const{prompt}=req.query;if(!prompt)return res.json({status:false,creator:C(),error:'Missing prompt'});res.json({status:true,creator:C(),prompt,result:img(prompt,'flux-realism')});});
router.get('/translate', async(req,res)=>{const{text,to='english',from='auto'}=req.query;if(!text)return res.json({status:false,creator:C(),error:'Missing text'});try{const r=await axios.get(`https://api.mymemory.translated.net/get?q=${encodeURIComponent(text)}&langpair=${from}|${to.slice(0,2).toLowerCase()}`,{timeout:10000});res.json({status:true,creator:C(),original:text,translated:r.data.responseData.translatedText,from,to});}catch(e){res.json({status:false,creator:C(),error:e.message});}});
router.get('/summarize', async(req,res)=>{const{text}=req.query;if(!text)return res.json({status:false,creator:C(),error:'Missing text'});try{res.json({status:true,creator:C(),result:await poll(`Summarize in 3-5 sentences:\n\n${text}`)});}catch(e){res.json({status:false,creator:C(),error:e.message});}});
router.get('/roast',     async(req,res)=>{const{name='someone',language='english'}=req.query;try{res.json({status:true,creator:C(),target:name,result:await poll(`Write a funny playful roast of "${name}" in ${language}. Humorous, not mean.`)});}catch(e){res.json({status:false,creator:C(),error:e.message});}});
router.get('/code',      async(req,res)=>{const{prompt,language='javascript'}=req.query;if(!prompt)return res.json({status:false,creator:C(),error:'Missing prompt'});try{res.json({status:true,creator:C(),language,result:await poll(`Write clean commented ${language} code for: ${prompt}. Return only code.`)});}catch(e){res.json({status:false,creator:C(),error:e.message});}});
router.get('/caption',   async(req,res)=>{const{topic,platform='instagram',tone='casual'}=req.query;if(!topic)return res.json({status:false,creator:C(),error:'Missing topic'});try{res.json({status:true,creator:C(),topic,platform,result:await poll(`Write a ${tone} ${platform} caption for: "${topic}". Include relevant hashtags.`)});}catch(e){res.json({status:false,creator:C(),error:e.message});}});
router.get('/story',     async(req,res)=>{const{prompt,genre='fiction',length='short'}=req.query;if(!prompt)return res.json({status:false,creator:C(),error:'Missing prompt'});try{res.json({status:true,creator:C(),genre,result:await poll(`Write a ${length} ${genre} story about: ${prompt}`)});}catch(e){res.json({status:false,creator:C(),error:e.message});}});
router.get('/bio',       async(req,res)=>{const{name,profession,style='professional'}=req.query;if(!name||!profession)return res.json({status:false,creator:C(),error:'Missing name and profession'});try{res.json({status:true,creator:C(),result:await poll(`Write a ${style} bio for ${name}, a ${profession}. Under 150 words.`)});}catch(e){res.json({status:false,creator:C(),error:e.message});}});
router.get('/lyrics2song',async(req,res)=>{const{title,genre='pop',artist}=req.query;if(!title)return res.json({status:false,creator:C(),error:'Missing title'});try{res.json({status:true,creator:C(),title,genre,result:await poll(`Write original ${genre} song lyrics titled "${title}"${artist?` in the style of ${artist}`:''}. Include verse, chorus, bridge.`)});}catch(e){res.json({status:false,creator:C(),error:e.message});}});
module.exports=router;