const express=require('express'),router=express.Router(),axios=require('axios'),{C}=require('../middleware/auth');
async function cobalt(url,opts={}){const r=await axios.post('https://cobalt.tools/api/json',{url,vCodec:'h264',vQuality:opts.quality||'720',aFormat:'mp3',isAudioOnly:opts.audioOnly||false,disableMetadata:true},{headers:{'Accept':'application/json','Content-Type':'application/json'},timeout:25000});return r.data;}
router.get('/ytmp3',     async(req,res)=>{const{url}=req.query;if(!url)return res.json({status:false,creator:C(),error:'Missing url'});try{const d=await cobalt(url,{audioOnly:true});if(d.url)res.json({status:true,creator:C(),url:d.url,filename:d.filename||'audio.mp3',quality:'128kbps',format:'mp3'});else res.json({status:false,creator:C(),error:'Cannot extract audio',details:d});}catch(e){res.json({status:false,creator:C(),error:e.message});}});
router.get('/ytmp4',     async(req,res)=>{const{url,quality='720'}=req.query;if(!url)return res.json({status:false,creator:C(),error:'Missing url'});try{const d=await cobalt(url,{quality});if(d.url)res.json({status:true,creator:C(),url:d.url,filename:d.filename||'video.mp4',quality:quality+'p',format:'mp4'});else res.json({status:false,creator:C(),error:'Cannot extract video',details:d});}catch(e){res.json({status:false,creator:C(),error:e.message});}});
router.get('/ytinfo',    async(req,res)=>{const{url}=req.query;if(!url)return res.json({status:false,creator:C(),error:'Missing url'});try{const r=await axios.get(`https://noembed.com/embed?url=${encodeURIComponent(url)}`,{timeout:8000});if(r.data.error)return res.json({status:false,creator:C(),error:r.data.error});res.json({status:true,creator:C(),result:{title:r.data.title,author:r.data.author_name,thumbnail:r.data.thumbnail_url,width:r.data.width,height:r.data.height}});}catch(e){res.json({status:false,creator:C(),error:e.message});}});
router.get('/tiktok',    async(req,res)=>{const{url}=req.query;if(!url)return res.json({status:false,creator:C(),error:'Missing url'});try{const d=await cobalt(url);if(d.url||d.picker)res.json({status:true,creator:C(),url:d.url||null,picker:d.picker||null,no_watermark:true});else res.json({status:false,creator:C(),error:'Cannot download TikTok',details:d});}catch(e){res.json({status:false,creator:C(),error:e.message});}});
router.get('/instagram', async(req,res)=>{const{url}=req.query;if(!url)return res.json({status:false,creator:C(),error:'Missing url'});try{const d=await cobalt(url);if(d.url||d.picker)res.json({status:true,creator:C(),url:d.url||null,picker:d.picker||null});else res.json({status:false,creator:C(),error:'Cannot download. Post must be public.',details:d});}catch(e){res.json({status:false,creator:C(),error:e.message});}});
router.get('/twitter',   async(req,res)=>{const{url}=req.query;if(!url)return res.json({status:false,creator:C(),error:'Missing url'});try{const d=await cobalt(url);if(d.url||d.picker)res.json({status:true,creator:C(),url:d.url||null,picker:d.picker||null});else res.json({status:false,creator:C(),error:'Cannot download Twitter/X media',details:d});}catch(e){res.json({status:false,creator:C(),error:e.message});}});
router.get('/facebook',  async(req,res)=>{const{url}=req.query;if(!url)return res.json({status:false,creator:C(),error:'Missing url'});try{const d=await cobalt(url);if(d.url)res.json({status:true,creator:C(),url:d.url,filename:d.filename||'fb_video.mp4'});else res.json({status:false,creator:C(),error:'Cannot download. Video must be public.',details:d});}catch(e){res.json({status:false,creator:C(),error:e.message});}});
router.get('/pinterest', async(req,res)=>{const{url}=req.query;if(!url)return res.json({status:false,creator:C(),error:'Missing url'});try{const d=await cobalt(url);if(d.url||d.picker)res.json({status:true,creator:C(),url:d.url||null,picker:d.picker||null});else res.json({status:false,creator:C(),error:'Cannot download Pinterest media',details:d});}catch(e){res.json({status:false,creator:C(),error:e.message});}});
router.get('/soundcloud',async(req,res)=>{const{url}=req.query;if(!url)return res.json({status:false,creator:C(),error:'Missing url'});try{const d=await cobalt(url,{audioOnly:true});if(d.url)res.json({status:true,creator:C(),url:d.url,filename:d.filename||'track.mp3',format:'mp3'});else res.json({status:false,creator:C(),error:'Cannot download SoundCloud track',details:d});}catch(e){res.json({status:false,creator:C(),error:e.message});}});
router.get('/vimeo',     async(req,res)=>{const{url}=req.query;if(!url)return res.json({status:false,creator:C(),error:'Missing url'});try{const d=await cobalt(url);if(d.url)res.json({status:true,creator:C(),url:d.url,filename:d.filename||'vimeo.mp4'});else res.json({status:false,creator:C(),error:'Cannot download Vimeo video',details:d});}catch(e){res.json({status:false,creator:C(),error:e.message});}});
module.exports=router;